### ISSUE TITLE
MacOS Ventura

### ISSUE THREAD

**Issue by lettertennis** [KenDxD/Lenovo-Thinkpad-E560-Hackintosh#1]
Hi there, first ı gotta say thank you for sharing your work with us. I was wondering can you make macOS Ventura version of this efi file? ı've tried to use this on my Ventura running E560 laptop but it kept restarting when it was halfway through the apple logo. I realized you even added the boot chime, that's one of the things ı couldn't managed to work. So ı would be really appreciated if you can make Ventura version of the efi file. Thank you for your time

**Comment by KenDxD** [comment]
You're welcome, I'm still waiting for my new SSD that I ordered last week. If the SSD arrived tomorrow GMT +8 Philippines Time Zone, I will test it first and release it with OpenCore V0.9.4.

**Comment by KenDxD** [comment]
> You're welcome, I'm still waiting for my new SSD that I ordered last week. If the SSD arrived tomorrow GMT +8 Philippines Time Zone, I will test it first and release it with OpenCore V0.9.4.

this is based on rsdev69 config, I just improved it by patching and add kext to boost performance and battery life

**Comment by lettertennis** [comment]
ı've done clean install of Monterey using your efi file around 2 hours ago to see how monterey works on this device and its so far so good. I realized fans are more quiet then Ventura and it feels more responsive. The only thing that bothers me about Monterey is that there is no stage manager in it.  I was using rsdev69's efi file before and its was working really well on Ventura except bluetooth and hdmı wasn't functional and there was no boot chime in it. Im looking forward for your improvements for Ventura. Again thank you for your hard work

**Comment by KenDxD** [comment]
> ı've done clean install of Monterey using your efi file around 2 hours ago to see how monterey works on this device and its so far so good. I realized fans are more quiet then Ventura and it feels more responsive. The only thing that bothers me about Monterey is that there is no stage manager in it.  I was using rsdev69's efi file before and its was working really well on Ventura except bluetooth and hdmı wasn't functional and there was no boot chime in it. Im looking forward for your improvements for Ventura. Again thank you for your hard work

The boot chime was enabled on both Ventura and Monterey config. About stage manager, it was only available for macOS Ventura (check macOS Release Notes).

**Comment by KenDxD** [comment]
> ı've done clean install of Monterey using your efi file around 2 hours ago to see how monterey works on this device and its so far so good. I realized fans are more quiet then Ventura and it feels more responsive. The only thing that bothers me about Monterey is that there is no stage manager in it.  I was using rsdev69's efi file before and its was working really well on Ventura except bluetooth and hdmı wasn't functional and there was no boot chime in it. Im looking forward for your improvements for Ventura. Again thank you for your hard work

https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/assets/41190270/fbd02caf-314e-48af-b31b-17da20d3ee6d

Releasing soon, still on testing

**Comment by lettertennis** [comment]
I’m sorry for the late reply. I’ve installed Ventura using your efi file yesterday and I was surprised that you managed to work Bluetooth. I thought it wasn’t possible for my Bluetooth device and sleep was working flawlessly. It’s seem like you really did a good job. The only problem I had; I used SMBios generater to generate my own Serial Number. When I apply the changes on the config.plist laptop gave me Mac/startup error and didn’t boot. How should I generate the Seriel Number using SMBios or using Opencore?

**Comment by lettertennis** [comment]
> > ı've done clean install of Monterey using your efi file around 2 hours ago to see how monterey works on this device and its so far so good. I realized fans are more quiet then Ventura and it feels more responsive. The only thing that bothers me about Monterey is that there is no stage manager in it.  I was using rsdev69's efi file before and its was working really well on Ventura except bluetooth and hdmı wasn't functional and there was no boot chime in it. Im looking forward for your improvements for Ventura. Again thank you for your hard work
> 
>  VID20230818183338.mp4 
> 
> Releasing soon, still on testing

Will be waiting :)

**Comment by KenDxD** [comment]
> I’m sorry for the late reply. I’ve installed Ventura using your efi file yesterday and I was surprised that you managed to work Bluetooth. I thought it wasn’t possible for my Bluetooth device and sleep was working flawlessly. It’s seem like you really did a good job. The only problem I had; I used SMBios generater to generate my own Serial Number. When I apply the changes on the config.plist laptop gave me Mac/startup error and didn’t boot. How should I generate the Seriel Number using SMBios or using Opencore?

Use SMBiosGen by corpnewt

First install latest update of macserial (select 1)
Then select 2 and, drag and drop your config plist.
Generate SMBIOS:
`MacBookPro14,1` for Ventura
`MacBookPro13,1` for Monterey

**Comment by KenDxD** [comment]
Sorry for the late reply, Im so busy patching for macOS Sonoma

**Comment by lettertennis** [comment]
no pr

> Sorry for the late reply, Im so busy patching for macOS Sonoma

No problem at all, ı see that you are really putting hard work for this job. Btw i've managed to generate the series number using smbios. I didn't know that ı should've generate UUID number too. That was the reason why ı didn't succeed in the first place. And at the latest Ventura file that you released ı was so surprise that you actually made hdmı working, when ı search the web there were things like hdmı isn't working on on this device,but it definitely works now. Again thank you for your hard work keep it up!
