### ISSUE TITLE
MacOS Sonoma EFI

### ISSUE THREAD

**Issue by lettertennis** [KenDxD/Lenovo-Thinkpad-E560-Hackintosh#2]
Hello there, I was wondering if you were going to release an EFI file for macOS Sonoma.👀

**Comment by KenDxD** [comment]
> Hello there, I was wondering if you were going to release an EFI file for macOS Sonoma.👀

Sorry for the late reply Im so busy because of my work. You can use my `macOS Ventura` EFI and change the SMBIOS to `MacBookPro15,1` then update the Intel Wifi Kext to `macOS Sonoma` and also update to the latest version of `Whatevergreen` and `Lilu` kext. Do not touch or reconfigure the `DeviceProperties` because it work out of the box, only change what I mention and there is no currently fix/patch on Bluetooth for `macOS Sonoma`.

Sent from Github Mobile

**Comment by KenDxD** [comment]
> Hello there, I was wondering if you were going to release an EFI file for macOS Sonoma.👀

Can you test this [release](https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/releases/tag/v2023.10.18) it include Sonoma but the Bluetooth is not working, I'm trying to make it work but no luck, but I manage to fix the Function Key that's not work after waking on sleep.

**Comment by lettertennis** [comment]
Hello there again. Yeah, it's been a while, and sorry for replying a little late there is just a lot going on these days. So i started preparing a USB installer for Sonoma when ı noticed you've released the file. But for some reason, the efi's smbios isn't configured and installer fails halfway through the process (Mac/startup). I believe I've done everything correctly as of your and Dortania's guide's directions. Let me tell you everything I've done but failed every time:  
1. First, I've got the full installer from apple's servers (softwareupdate --fetch-full-installer --full-installer-version 14.0)
2. Second I've got your Sonoma efi and headed to to the smbios ı done the 1 to 4 process to the efi file (1. Install/Update MacSerial 2. Select config.plist 3. Generate SMBIOS 4. Generate UUID) Mac model MacBookPro15,1 
3. Once the installer finished downloading i created the bootable usb. (sudo /Applications/Install\ macOS\ Sonoma.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume)
4. I mounted the efi partition of the usb and placed the processed efi and restarted and it did not boot.  
Im not sure where did i messed up or missed something but this process is literally the same as i do to the Ventura and it was working every time. By the way, i forgot to mention. I was able to upgrade to the Sonoma but i fresh installed Ventura with the old efi then after the installation I replaced the efi with your's freshly smbios generated EFI. I was able to upgrade using normal software update section from settings app but none of the ports are working and there is a little text bottom right corner of the screen of open core booter. It says REL-095-2023-09-11 
But even tho ı couldn't really experience Sonoma, ı really can tell the difference between the old efi. Sleep,buttons and battery management definitely got really better. So this was my problem that ı was having and ım still trying to solve this but if you have any ideas why this might be happening I really need help. 😁

**Comment by KenDxD** [comment]
> Hello there again. Yeah, it's been a while, and sorry for replying a little late there is just a lot going on these days. So i started preparing a USB installer for Sonoma when ı noticed you've released the file. But for some reason, the efi's smbios isn't configured and installer fails halfway through the process (Mac/startup). I believe I've done everything correctly as of your and Dortania's guide's directions. Let me tell you everything I've done but failed every time:  
> 
> 1. First, I've got the full installer from apple's servers (softwareupdate --fetch-full-installer --full-installer-version 14.0)
> 2. Second I've got your Sonoma efi and headed to to the smbios ı done the 1 to 4 process to the efi file (1. Install/Update MacSerial 2. Select config.plist 3. Generate SMBIOS 4. Generate UUID) Mac model MacBookPro15,1
> 3. Once the installer finished downloading i created the bootable usb. (sudo /Applications/Install\ macOS\ Sonoma.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume)
> 4. I mounted the efi partition of the usb and placed the processed efi and restarted and it did not boot.     
>    Im not sure where did i messed up or missed something but this process is literally the same as i do to the Ventura and it was working every time.    By the way, i forgot to mention. I was able to upgrade to the Sonoma but i fresh installed Ventura with the old efi then after the installation I replaced the efi with your's freshly smbios generated EFI. I was able to upgrade using normal software update section from settings app but none of the ports are working and there is a little text bottom right corner of the screen of open core booter. It says REL-095-2023-09-11
>    But even tho ı couldn't really experience Sonoma, ı really can tell the difference between the old efi. Sleep,buttons and battery management definitely got really better. So this was my problem that ı was having and ım still trying to solve this but if you have any ideas why this might be happening I really need help. 😁

can you please send me your debug log for both Opencore bootloader and Lilu/Whatevergreen? Just read how to debug on opencore GitHub page or on Dortania guide. I tried it on my other hdd just to test and the config works for me, I don't know why it won't work. It so helpful if you can send it so that I can adjust or fix if the EFI configs the real problem.

**Comment by lettertennis** [comment]
I am really sorry for not replying sooner. I get home really late these so I didn't had really much time. So i debugged efi using this guide [ ](https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/debug.md)  and after I did that a long list of texts slided through the Lenovo boot. I searched a lot for how to spot debut log for open core configurator bootloader but I really cound't find it. The only thing that I could find was a file in the efi partition after debugging appeared that I've attached it down below and another change was REL-095-2023-09-11 turned to DBG-095-2023-09-11
And I guess ı didn't mention about something in my last comment I was able to freshly install macOS Sonoma with ports working but wifi doesn't working (but I guess bluetooth were working tho) using V2 efi file of Ventura the only thing that ı changed was update the efi and change SMBIOS. 
I'am not sure if I gave you some helpful information but I really did tried to find the debug logs. I am really new in hacintoshing so i'am sorry if this didn't help. But if you can tell me how to see the logs ı would be so happy to help. 
[opencore-2023-10-29-125752.txt](https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/files/13198132/opencore-2023-10-29-125752.txt)

Update: 11:51pm GMT +8 Philippine Time

I forgot to change the value of `USBPorts.kext` Info.plist for `Monterey` and `Sonoma`, so it wont boot to recovery because it check for` XHCI`, `v2023.08.18-v2` doesn't have a mapped usb port so it doesn't affected. The default value is `MacBookPro14,1` so it only works on Ventura. I will release a v2 of 2023-10-18 build later. Once again, thank you for the information and I will make sure that I won't repeat this mistake again. 
Can you be my tester? I don't have any extra SSD right now, I'm just using my old 8 years old 5400rpm HDD for debugging (reinstalling every macOS version for fix), so I can't keep up releasing a fixes, I used my 120Gb SSD right know and daily driver on Ventura.

**Comment by KenDxD** [comment]
> I am really sorry for not replying sooner. I get home really late these so I didn't had really much time. So i debugged efi using this guide [ ](https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/debug.md) and after I did that a long list of texts slided through the Lenovo boot. I searched a lot for how to spot debut log for open core configurator bootloader but I really cound't find it. The only thing that I could find was a file in the efi partition after debugging appeared that I've attached it down below and another change was REL-095-2023-09-11 turned to DBG-095-2023-09-11 And I guess ı didn't mention about something in my last comment I was able to freshly install macOS Sonoma with ports working but wifi doesn't working (but I guess bluetooth were working tho) using V2 efi file of Ventura the only thing that ı changed was update the efi and change SMBIOS. I'am not sure if I gave you some helpful information but I really did tried to find the debug logs. I am really new in hacintoshing so i'am sorry if this didn't help. But if you can tell me how to see the logs ı would be so happy to help. [opencore-2023-10-29-125752.txt](https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/files/13198132/opencore-2023-10-29-125752.txt)

thank you for giving me a hint, I guess I put a wrong efi config on the release, I will fix it on the next release.

**Comment by lettertennis** [comment]
> I am really sorry for not replying sooner. I get home really late these so I didn't had really much time. So i debugged efi using this guide [ ](https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/debug.md) and after I did that a long list of texts slided through the Lenovo boot. I searched a lot for how to spot debut log for open core configurator bootloader but I really cound't find it. The only thing that I could find was a file in the efi partition after debugging appeared that I've attached it down below and another change was REL-095-2023-09-11 turned to DBG-095-2023-09-11 And I guess ı didn't mention about something in my last comment I was able to freshly install macOS Sonoma with ports working but wifi doesn't working (but I guess bluetooth were working tho) using V2 efi file of Ventura the only thing that ı changed was update the efi and change SMBIOS. I'am not sure if I gave you some helpful information but I really did tried to find the debug logs. I am really new in hacintoshing so i'am sorry if this didn't help. But if you can tell me how to see the logs ı would be so happy to help. [opencore-2023-10-29-125752.txt](https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/files/13198132/opencore-2023-10-29-125752.txt)
> 
> Update: 11:51pm GMT +8 Philippine Time
> 
> I forgot to change the value of `USBPorts.kext` Info.plist for `Monterey` and `Sonoma`, so it wont boot to recovery because it check for` XHCI`, `v2023.08.18-v2` doesn't have a mapped usb port so it doesn't affected. The default value is `MacBookPro14,1` so it only works on Ventura. I will release a v2 of 2023-10-18 build later. Once again, thank you for the information and I will make sure that I won't repeat this mistake again. Can you be my tester? I don't have any extra SSD right now, I'm just using my old 8 years old 5400rpm HDD for debugging (reinstalling every macOS version for fix), so I can't keep up releasing a fixes, I used my 120Gb SSD right know and daily driver on Ventura.

Oh no problem at all. Yeah of course, I think I can be your tester but sometimes it may take a while for me to work on it because of my job but I'd be happy if I can help 😄

**Comment by KenDxD** [comment]
> > I am really sorry for not replying sooner. I get home really late these so I didn't had really much time. So i debugged efi using this guide [ ](https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/debug.md) and after I did that a long list of texts slided through the Lenovo boot. I searched a lot for how to spot debut log for open core configurator bootloader but I really cound't find it. The only thing that I could find was a file in the efi partition after debugging appeared that I've attached it down below and another change was REL-095-2023-09-11 turned to DBG-095-2023-09-11 And I guess ı didn't mention about something in my last comment I was able to freshly install macOS Sonoma with ports working but wifi doesn't working (but I guess bluetooth were working tho) using V2 efi file of Ventura the only thing that ı changed was update the efi and change SMBIOS. I'am not sure if I gave you some helpful information but I really did tried to find the debug logs. I am really new in hacintoshing so i'am sorry if this didn't help. But if you can tell me how to see the logs ı would be so happy to help. [opencore-2023-10-29-125752.txt](https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh/files/13198132/opencore-2023-10-29-125752.txt)
> > 
> > Update: 11:51pm GMT +8 Philippine Time
> > 
> > I forgot to change the value of `USBPorts.kext` Info.plist for `Monterey` and `Sonoma`, so it wont boot to recovery because it check for` XHCI`, `v2023.08.18-v2` doesn't have a mapped usb port so it doesn't affected. The default value is `MacBookPro14,1` so it only works on Ventura. I will release a v2 of 2023-10-18 build later. Once again, thank you for the information and I will make sure that I won't repeat this mistake again. Can you be my tester? I don't have any extra SSD right now, I'm just using my old 8 years old 5400rpm HDD for debugging (reinstalling every macOS version for fix), so I can't keep up releasing a fixes, I used my 120Gb SSD right know and daily driver on Ventura.
> 
> Oh no problem at all. Yeah of course, I think I can be your tester but sometimes it may take a while for me to work on it because of my job but I'd be happy if I can help 😄

It's okay as long as I won't reinstall and wait for another hour just to fix a bug. Do you have Discord so that I can send you the file later. I already recompile V2 of Sonoma with new USB Mapping using Corpnewt tools ditching the Hackintool method that I used from this build. Its fast and unlock the full potential of USB 3.0 SuperSpeed. I will integrate it to Ventura and Monterey as well.

**Comment by lettertennis** [comment]
I didn't have a discord account so ı just created one and wow you've already released the file that's amazing.

**Comment by KenDxD** [comment]
> I didn't have a discord account so ı just created one (smworld.) and wow you've already released the file that's amazing. 

Only the source code, I have the unreleased version here rn and it can boot on Sonoma based on v2023.10.18, the wifi is working even on recovery, the only problem right now is bluetooth

**Comment by lettertennis** [comment]
That's awesome I'll replace the efi with the new one in a minute.
